export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const SET_PRIMARY_DATA = 'SET_PRIMARY_DATA';
export const LOAD_MORE_NEWS = 'LOAD_MORE_NEWS';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const NEXT_LIST = 'NEXT_LIST';
export const PREVIOUS_LIST = 'PREVIOUS_LIST';
